apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spotify
  description: The Spotify web API
  tags:
    - spotify
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition:
    $text: https://github.com/rneild/backstagetest/blob/main/profileservice.yaml
